#!/bin/sh

PATH=/sbin:/bin:/usr/bin

DAEMON1="/usr/bin/playmusic-daemon"
DAEMON2="/usr/bin/Detect-USB"

test -f ${DAEMON1} || exit 0
test -f ${DAEMON2} || exit 0

startdaemon1(){
  modprobe snd-bcm2835 #This will wire up the sound card with alsa
  start-stop-daemon -b --start --quiet --exec ${DAEMON1}
}

stopdaemon1(){
  start-stop-daemon --stop --quiet --exec ${DAEMON1}
}
startdaemon2(){
  sudo modprobe snd-bcm2835 #This will wire up the sound card with alsa
  start-stop-daemon -b --start --quiet --exec ${DAEMON2}
}

stopdaemon2(){                                                         
  start-stop-daemon --stop --quiet --exec ${DAEMON2}    
}                                                   
startdaemon1  
