#!/bin/sh                                                                       
oldDevices="/newFiles"                                                          
newDevices="/newFiles2"                                                         
songList="/songs.txt"                                                           
mountDirectory="/media"                                                         
PLAYER="/media"                                                                 
songs="/songsFile/SongsList"                                                    
USBFlag="/songsFile/USBDetect"                                                  
                                                                                
                                                                                
                                                                                
if [ ! -f "$songs" ]; then                                                      
        touch $songs                                                            
        chmod 777 $songs                                                        
fi                                                                              
                                                                                
if [ ! -f "$USBFlag" ]; then                                                    
        touch $USBFlag                                                          
        echo "1" > $USBFlag                                                     
fi                                                                              
                                                                                
if [ ! -f "$oldDevices" ]; then                                                 
        touch $oldDevices     
        echo "0" > $oldDevices                                                  
fi                                                                              
                                                                                
                                                                                
search=$(find /dev/sd*)                                                         
if  [ ! -z "$search"  ] ; then                                                  
                echo $search | tr " " "\n"> $oldDevices                         
fi                                                                              
                                                                                
while true; do                                                                  
        sleep 1                                                                 
        #search2=$(find /dev/sd*)                                               
        search2="$(fdisk -l /dev/sd* | grep -v 'Unknown' | grep -v 'Empty' | awk
        echo $search2 | tr " " "\n"> $newDevices                                
        if cmp -s $oldDevices $newDevices ; then                                
                echo 'The file "%s" is the same as "%s"\n' "$file1" "$file2" > /
        else                                                                    
                echo "something changed"                                        
                cp  $newDevices $oldDevices                                     
                                                                                
                echo "1" > $USBFlag                                             
               echo "something Change"                                          
        fi 
        while read p; do                                                        
                #if grep -qs $p /proc/mounts; then                              
                #    echo "$p is mounted." > /dev/null                          
               #        else                                                    
                    echo "$p is not mounted." #> /dev/null                      
                    tempV=$(expr substr ${p} 5 10)                              
                    #echo $tempV                                                
                    mkdir -p $mountDirectory/"$tempV"                           
                   mount $p $mountDirectory/"$tempV"                            
                                                                                
        #       fi                                                              
        done < $oldDevices                                                      
                                                                                
     if [[ $( cat $USBFlag ) == '1' ]] ; then                                   
         find $PLAYER -iname "*mp3" | while read song                           
         do                                                                     
            echo "$song">> $songs                                               
         done                                                                   
         echo 0 > $USBFlag                                                      
      fi                                                                        
        #find / -depth -name '*.mp3' > $songList                                
done 
