#!/bin/sh
set -e

PLAYER="/media"
songs="/songsFile/SongsList"
CommandLine="/songsFile/cmdState"
SongNumber="/songsFile/SongNumberFile"
playState="/songsFile/playStateFile" 
SongCounter="/songsFile/SongCounterFile"


test -d ${PLAYER} || exit 1

mkdir -p /songsFile



if [ ! -e $playState ]                                                 
then                                                                            
 touch $playState                                                    
 chmod 777 $playState                                                
fi 
 
echo 0 > $playState 

if [ ! -e $SongNumber ]                                                 
then                                                                            
 touch $SongNumber                                                    
 chmod 777 $SongNumber                                                  
fi  


if [ ! -e $CommandLine ] ; then
   touch $CommandLine
   chmod 777 $CommandLine
   echo 0 > $CommandLine
fi
   echo 0 > $CommandLine          

                                            
 
                                            
functionToSetArrayOfMusic(){                
                                          
Song_Number=1                
Min_NumberOfSong=1           
button_state=0               
FirstTimeFlag=0              
PlayingFlag=0           
                             
                                                                        
}                         
functionToSetArrayOfMusic                                                       
                                            
                                            
if [ ! -d /sys/class/gpio/gpio4 ] ; then # check if export process has done befo
     # Ask kernal to export the virtual file to control gpio                    
    echo "4" > /sys/class/gpio/export                                           
    # Set pin direction as input                                                
    echo "in" > /sys/class/gpio/gpio4/direction                                 
fi                                                                              
if [ ! -d /sys/class/gpio/gpio17 ] ; then # check if export process has done bef
     # Ask kernal to export the virtual file to control gpio                    
    echo "17" > /sys/class/gpio/export                                          
 # Set pin direction as input                                                   
    echo "in" > /sys/class/gpio/gpio17/direction                                
fi                                                                              
if [ ! -d /sys/class/gpio/gpio18 ] ; then # check if export process has done bef
     # Ask kernal to export the virtual file to control gpio                    
    echo "18" > /sys/class/gpio/export                                          
    # Set pin direction as input     
    # Set pin direction as input                                                
    echo "in" > /sys/class/gpio/gpio18/direction                                
fi                                                                              
if [ ! -d /sys/class/gpio/gpio27 ] ; then # check if export process has done bef
     # Ask kernal to export the virtual file to control gpio                    
    echo "27" > /sys/class/gpio/export                                          
    # Set pin direction as input                                                
    echo "in" > /sys/class/gpio/gpio27/direction                                
fi                                                                              
                                                                                
                                                                                
while true                                                                      
do                                                                              
                                                                                
   song_counter=$( cat $SongCounter )
                                                                          
   if [[ $( cat $CommandLine ) ==  '1' ]] ; then  #play                          
        if [ $song_counter -eq 0 ] ; then
           echo "No .MP3 files found"
           sleep 0.4
        else
            Song_Number=$( cat $SongNumber ) 
            music=$( awk 'NR==n' n=$Song_Number $songs )                      
          
            echo "MP3 Playing > [$(basename ${music})]" 
            sleep 0.3                                                                                    
            if [[ $( cat $playState ) == '1' ]]                                          
              then                                                              
              killall -CONT mpg123 2> /dev/null                                        
              sleep 0.4                                                                                                    
            else
              mpg123 -q ${music} &
              sleep 0.4
            fi                                                                                                            
         fi   
         echo 0 > $CommandLine                                            
                                                                          
 elif [[ $( cat $CommandLine ) ==  '2' ]] ; then  # 'pause'                      
        
        if [ $song_counter -eq 0 ] ; then                                             
           echo "No .MP3 files found"   
           sleep 0.4                                        
        else     
           Song_Number=$( cat $SongNumber ) 
           music=$( awk 'NR==n' n=$Song_Number $songs )                                                                                                
           echo "MP3 Paused > [$(basename ${music})]"                             
           sleep 0.4
           killall -STOP  mpg123 2> /dev/null                                                                                                          
           echo 1 > $playState
                                                             
        fi      
        echo 0 > $CommandLine                                              
                                                                              
 elif [[ $( cat $CommandLine ) ==  '3' ]] ; then  # next                         
        if [ $song_counter -eq 0 ] ; then                                             
           echo "No .MP3 files found"  
           sleep 0.4                                         
        else       
           killall -KILL mpg123 2> /dev/null                                                                        
           Song_Number=$( cat $SongNumber ) 
     
           if [ $Song_Number -lt $song_counter ] ; then                                                                                       
            Song_Number=$(($Song_Number+1))   
            sleep 0.4                                                                                   
           else
            Song_Number=$song_counter  
            sleep 0.4
           fi  
           echo $Song_Number > $SongNumber
           music=$( awk 'NR==n' n=$Song_Number $songs )                          
           echo "MP3 Playing > [$(basename ${music})]"                           
           mpg123 -q ${music} &                                                  
                                                                                                                                             
        fi  
        echo 0 > $CommandLine                                                                      
       
  elif [[ $( cat $CommandLine ) ==  '4' ]] ; then  # previous                     
       if [ $song_counter -eq 0 ] ; then                                              
           echo "No .MP3 files found"                                           
        else     
           killall -KILL mpg123 2> /dev/null             
           sleep 0.4                     
           Song_Number=$( cat $SongNumber )                                        
                                               
           if [ $Song_Number -gt $Min_NumberOfSong ] ; then                                                               
             Song_Number=$(($Song_Number-1))    
             sleep 0.4                                                                      
           else
             Song_Number=1
             sleep 0.4                                                                                                                 
           fi
           echo $Song_Number > $SongNumber 
           music=$( awk 'NR==n' n=$Song_Number $songs )                        
           echo "MP3 Playing > [$(basename ${music})]"                         
           mpg123 -q ${music} &                                                
                                                                                 
       fi
       echo 0 > $CommandLine                                                                      
                                                                                
  elif [[ $( cat $CommandLine ) ==  '5' ]] ; then  # shuffle                      
       if [ $song_counter -eq 0 ] ; then                                              
           echo "No .MP3 files found"   
           sleep 0.4                                        
       else
                                                
           Random_Line=$(((RANDOM%song_counter) + 1))  
           echo $Random_Line > $SongNumber                                        
                                                                                                                                   
            killall -KILL mpg123 2> /dev/null
            sleep 0.4
            Song_Number=$Random_Line
            echo $Song_Number > $SongNumber                                                                                 
            music=$( awk 'NR==n' n=$Song_Number $songs )                        
            echo "MP3 Playing > [$(basename ${music})]"                         
            mpg123 -q ${music} &  
                                                                                        
      fi                          
      echo 0 > $CommandLine                                              
                                                                                
                                                                                
   elif [ $(cat /sys/class/gpio/gpio4/value) == '1' ] ; then #if anyone pus       
            #toggle button state 
        if [ $song_counter -eq 0 ] ; then                                              
           echo "No .MP3 files found"                                           
        else                                                    
            if [ $FirstTimeFlag -eq 0 ] ; then                                  
              music=$( awk 'NR==n' n=$Song_Number $songs )                      
	      mpg123 -q ${music} &                                                
	      echo "MP3 Playing > [$(basename ${music})]"  
              FirstTimeFlag=1                                                   
              PlayingFlag=1                                                     
              button_state=1                                                    
              sleep 0.5                                                         
              continue                                                          
            fi                                                                  
            if [ $button_state -eq 0 ]                                          
              then                                                              
              echo "MP3 Playing > [$(basename ${music})]"   
              killall -CONT mpg123 &                                            
              PlayingFlag=1                                                     
              button_state=1                                                    
              sleep 0.4                                                         
            elif [ $button_state -eq 1 ]                                        
              then                                                              
              echo "MP3 Puased > [$(basename ${music})]"                        

              killall -STOP  mpg123 &                                           
              PlayingFlag=0                                                     
              button_state=0                                                    
              sleep 0.4 # to allow finger release                               
            fi                                                                  
         fi                                                              
                                                                                
   elif [ $(cat /sys/class/gpio/gpio17/value) == '1' ] ; then #next  
         sleep 0.5             
         if [ $song_counter -eq 0 ] ; then                                             
           echo "No .MP3 files found"                                           
        else      
            if [ $PlayingFlag -eq 1 ] ; then  
              killall -KILL mpg123 &                                            
              Song_Number=$( cat $SongNumber )                                   
              if [ $Song_Number -lt $song_counter ] ; then                         
                Song_Number=$(($Song_Number+1))    
                sleep 0.4                                 
              else                                                              
                Song_Number=$song_counter
                sleep 0.4                                           
              fi                                                                   
                                        
              music=$( awk 'NR==n' n=$Song_Number $songs )                         
              echo "MP3 Playing > [$(basename ${music})]" 
              echo $Song_Number > $SongNumber 
              mpg123 -q ${music} &                               
            fi                                                                
        fi                                                                  
                                                                 
   elif [ $(cat /sys/class/gpio/gpio18/value) == '1' ] ; then #prev               
         sleep 0.5        
         if [ $song_counter -eq 0 ] ; then                                             
           echo "No .MP3 files found"                                           
        else     
           if [ $PlayingFlag -eq 1 ] ; then    
              killall -KILL mpg123 &                                          
             # sleep 0.5
              #pidof mpg123 | xargs kill -9 >/dev/null     
              Song_Number=$( cat $SongNumber )                               
              if [ $Song_Number -gt $Min_NumberOfSong ] ; then                               
                Song_Number=$(($Song_Number-1))                                    
              else                                                                 
                 Song_Number=1                                                      
              fi                                          
              echo $Song_Number > $SongNumber                                  
              music=$( awk 'NR==n' n=$Song_Number $songs )                    
              echo "MP3 Playing > [$(basename ${music})]"                     
              mpg123 -q ${music} &                                               
              sleep 0.4                                                  
           fi                                                                  
        fi  
                                                                
   elif [ $(cat /sys/class/gpio/gpio27/value) == '1' ] ; then #Shuffel            
        sleep 0.5
        if [ $song_counter -eq 0 ] ; then                                              
           echo "No .MP3 files found"                                           
        else     
           if [ $PlayingFlag -eq 1 ] ; then                                   
             Random_Line=$(((RANDOM%song_counter) + 1))                           
             echo $Random_Line > $SongNumber                                      
                                                                                
             killall -KILL mpg123 &                                            
             Song_Number=$Random_Line                                            
             echo $Song_Number > $SongNumber                                     
             music=$( awk 'NR==n' n=$Song_Number $songs )                        
             echo "MP3 Playing > [$(basename ${music})]"                         
             mpg123 -q ${music} &                                                                                                                                    
           fi                                                                  
        fi                                                                
  fi                                                                              
done                                                                            
          
